kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  generateName: test-pvc-
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: powerstore
